= lsinv

The `lsinv.sh` `bash`-script allows on linux machines running an avahi-daemon and having avahi-utils
installed to list all available ITxPT inventory services. The default output is generated as a ```JSON``` array.

== Prerequisits

* The following tools need to be installed:
    ** avahi-daemon
    ** avahi-utils (for avahi-browse) 
    ** grepcidr 
    ** jq

* avahi-daemon disable for IPv6

If you don't already have a folder for github repos, Create one..
Ex:
[,shell]
----
sudo mkdir /opt/git
----
Then move into that folder
[,shell]
----
cd /opt/git
----

Then from there clone the lsinv repo
[,shell]
----
sudo git clone https://github.com/ITxPT/lsinv.git
----
This will create a subfolder named lsinv, move into that folder..
[,shell]
----
cd lsinv
----

_Note:_To make the script available as bash command use a symbolic link. Within the repository folder execute the following command:
[,shell]
----
sudo ln -s $(pwd)/lsinv.sh /usr/local/bin/lsinv
----


== Usage

Download repository and use tool directly from installation folder or copy ```/usr/local/bin```:
[,shell]
----
./lsinv.sh  -i 192.168.1.0/24
----

== Known issues

* Due to optional fields and the fact that JSON allows unsorted fields the CSV output is unreliable 
